language: node_js

services:
  - docker

node_js:
  - "14"

before_install:
  - npx prettier --check "./**/*.js"

install:
  - docker-compose build

script:
  - docker-compose up -d
  - docker-compose ps

after_script:
  - docker-compose stop
