language: node_js

services:
  - docker

node_js:
  - "14"

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - npx prettier --check "./**/*.js"
  - docker --version
  - docker-compose --version

install:
  - docker-compose build

script:
  - docker-compose up -d

after_script:
  - docker-compose stop
  - docker-compose ps
