language: node_js

services:
  - docker

node_js:
  - "14"

before_install:
  - npx prettier --check "./**/*.js"

install:
  - docker-compose build
  - docker-compose up -d

after_install:
  - docker-compose stop

script:
  - ./configure && make
