language: node_js

services:
  - docker

node_js:
  - "14"

stages:
  - tests
  - start
  - name: deploy
    if: (branch = main) AND (type != pull_request)

jobs:
  include:
    - stage: tests
      name: "prettier check"
      script: npx prettier --check "./**/*.js"
      script: npm run test

    - stage: deploy
      name: "build and deploy"
      before_install:
        - docker --version
        - docker-compose --version
      install:
        - docker-compose build
      script:
        - docker-compose up -d
        - docker-compose ps
        - docker-compose stop
        - docker-compose ps
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose push
