language: node_js

services:
  - docker

node_js:
  - "14"

srcipt:
  - npx prettier --check "./**/*.js"

before_install:
  - docker-compose build

install:
  - docker-compose up -d

after_install:
  - docker-compose stop
