language: node_js

services:
  - docker

node_js:
  - "14"

before_install:
  - npx prettier --check "./**/*.js"
  - docker --version
  - docker-compose --version

install:
  - docker-compose build

script:
  - docker-compose up -d

after_script:
  - docker-compose stop
  - docker-compose ps

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose push
