language: node_js

services:
  - docker

node_js:
  - "14"

stages:
  - test
  - name: deploy
    if: branch = master

before_install:
  - node --version
  - docker --version
  - docker-compose --version

jobs:
  include:
    - stage: "test"
      name: "prettier check"
      script: npx prettier --check "./**/*.js"
      install: skip
    - stage: deploy
      name: "push images to dockerhub"
      install:
        - docker-compose build
        - docker-compose up -d
        - docker-compose ps
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose push
      after_script:
        - docker-compose stop
        - docker-compose ps
