language: node_js

services:
  - docker

node_js:
  - "12"
  - "10"
  - "8"
  - "6"

before_install:
  - npm install -g npm@latest
  - npx prettier --check "./**/*.js"

install:
  - docker-compose up -d
  - docker-compose stop
